export const flights = [

  {
    id: 1,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Barcelona International Airport",
    arrival_airport_code: "BCN",
    departure_date: "15/10/2023",
    departure_time: "10:30",
    arrival_time: "14:45",
    elapsed_time: "4hours15min",
    price: "1250TL"
  },
  {
    id: 2,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Madrid Barajas Airport",
    arrival_airport_code: "MAD",
    departure_date: "20/10/2023",
    departure_time: "12:15",
    arrival_time: "16:30",
    elapsed_time: "3hours45min",
    price: "1350TL"
  },
  {
    id: 3,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Heathrow Airport",
    arrival_airport_code: "LHR",
    departure_date: "25/10/2023",
    departure_time: "09:45",
    arrival_time: "13:30",
    elapsed_time: "3hours45min",
    price: "1100TL"
  },
  {
    id: 4,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Paris Charles de Gaulle Airport",
    arrival_airport_code: "CDG",
    departure_date: "30/10/2023",
    departure_time: "14:20",
    arrival_time: "18:10",
    elapsed_time: "3hours50min",
    price: "1400TL"
  },
  {
    id: 5,
    departure_airport: "Istanbul Airport",
    departure_airport_code: "IST",
    arrival_airport: "Heathrow Airport",
    arrival_airport_code: "LHR",
    departure_date: "15/11/2023",
    departure_time: "10:30",
    arrival_time: "14:15",
    elapsed_time: "4hours45min",
    price: "1650TL"
  },
  {
    id: 6,
    departure_airport: "Ataturk Airport",
    departure_airport_code: "IST",
    arrival_airport: "Frankfurt Airport",
    arrival_airport_code: "FRA",
    departure_date: "20/12/2023",
    departure_time: "09:45",
    arrival_time: "13:30",
    elapsed_time: "3hours50min",
    price: "1250TL"
  },
  {
    id: 7,
    departure_airport: "Ataturk Airport",
    departure_airport_code: "IST",
    arrival_airport: "Frankfurt Airport",
    arrival_airport_code: "FRA",
    departure_date: "20/12/2023",
    departure_time: "09:45",
    arrival_time: "13:30",
    elapsed_time: "3hours50min",
    price: "1250TL"
  },
  {
    id: 8,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "09:45",
    arrival_time: "13:30",
    elapsed_time: "3hours50min",
    price: "1250TL"
  },
  {
    id: 9,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "10:30",
    arrival_time: "11:30",
    elapsed_time: "1hours",
    price: "2250TL"
  },
  {
    id: 10,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "12:30",
    arrival_time: "15:30",
    elapsed_time: "3hours",
    price: "1750TL"
  },
  {
    id: 11,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "16:30",
    arrival_time: "17:30",
    elapsed_time: "1hours",
    price: "4500TL"
  },
  {
    id: 12,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "01:30",
    arrival_time: "05:00",
    elapsed_time: "3hours30min",
    price: "4500TL"
  },
  {
    id: 13,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "01:30",
    arrival_time: "05:00",
    elapsed_time: "3hours30min",
    price: "4500TL"
  },
  {
    id: 14,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "02:30",
    arrival_time: "04:00",
    elapsed_time: "1hours30min",
    price: "1850TL"
  },
  {
    id: 15,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "07:15",
    arrival_time: "08:00",
    elapsed_time: "45min",
    price: "6250TL"
  },
  {
    id: 16,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "12:00",
    arrival_time: "14:00",
    elapsed_time: "2hours",
    price: "7800TL"
  },
  {
    id: 17,
    departure_airport: "Sabiha Gokçen Airport",
    departure_airport_code: "SAW",
    arrival_airport: "Valencia Airport",
    arrival_airport_code: "VLC",
    departure_date: "15/09/2023",
    departure_time: "13:00",
    arrival_time: "14:30",
    elapsed_time: "1hours30min",
    price: "5500TL"
  },
  {
    id: 18,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "15/09/2023",
    departure_time: "09:45",
    arrival_time: "13:30",
    elapsed_time: "3hours50min",
    price: "1250TL"
  },
  {
    id: 19,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "17/09/2023",
    departure_time: "10:30",
    arrival_time: "11:30",
    elapsed_time: "1hours",
    price: "2250TL"
  },
  {
    id: 20,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "17/09/2023",
    departure_time: "12:30",
    arrival_time: "15:30",
    elapsed_time: "3hours",
    price: "1750TL"
  },
  {
    id: 21,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "17/09/2023",
    departure_time: "16:30",
    arrival_time: "17:30",
    elapsed_time: "1hours",
    price: "4500TL"
  },
  {
    id: 22,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "17/09/2023",
    departure_time: "01:30",
    arrival_time: "05:00",
    elapsed_time: "3hours30min",
    price: "4500TL"
  },
  {
    id: 23,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "17/09/2023",
    departure_time: "01:30",
    arrival_time: "05:00",
    elapsed_time: "3hours30min",
    price: "4500TL"
  },
  {
    id: 24,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "17/09/2023",
    departure_time: "02:30",
    arrival_time: "04:00",
    elapsed_time: "1hours30min",
    price: "1850TL"
  },
  {
    id: 25,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "17/09/2023",
    departure_time: "07:15",
    arrival_time: "08:00",
    elapsed_time: "45min",
    price: "6250TL"
  },
  {
    id: 26,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "17/09/2023",
    departure_time: "12:00",
    arrival_time: "14:00",
    elapsed_time: "2hours",
    price: "7800TL"
  },
  {
    id: 27,
    departure_airport: "Valencia Airport",
    departure_airport_code: "VLC",
    arrival_airport: "Sabiha Gokçen Airport",
    arrival_airport_code: "SAW",
    departure_date: "17/09/2023",
    departure_time: "13:00",
    arrival_time: "14:30",
    elapsed_time: "1hours30min",
    price: "5500TL"
  },



]